<a href="https://colab.research.google.com/github/yanna-torres/CKP9011-ciencia-de-dados/blob/lista-01/lista01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lista 01 - Tratamento de dados

> Yanna Torres Gonçalves
>
> Mestrado em Ciências da Computação
>
> Matrícula: 587299

[https://youtu.be/tAFApvJZLHg](https://youtu.be/tAFApvJZLHg)

In [1]:
import pandas as pd
import numpy as np
import re

## a) Ler o dataset fakeTelegram.BR_2022.csv

Para facilitar o resuo nas próximas atividades, o dataset utilizado está disponível no mesmo respositório da lista.

[https://github.com/yanna-torres/CKP9011-ciencia-de-dados/blob/lista-01/data/fakeTelegram.BR_2022.csv](https://github.com/yanna-torres/CKP9011-ciencia-de-dados/blob/lista-01/data/fakeTelegram.BR_2022.csv)

In [2]:
data_url = "https://media.githubusercontent.com/media/yanna-torres/CKP9011-ciencia-de-dados/refs/heads/lista-01/data/fakeTelegram.BR_2022.csv"

df = pd.read_csv(data_url)

In [3]:
df.head(10)

,date_message,id_member_anonymous,id_group_anonymous,media,media_type,media_url,has_media,has_media_url,trava_zap,text_content_anonymous,dataset_info_id,date_system,score_sentiment,score_misinformation,id_message,message_type,messenger,media_name,media_md5
0,2022-10-05 06:25:04,1078cc958f0febe28f4d03207660715f,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,Então é Fato Renato o áudio que eu ouvi no wha...,5,2022-10-05 06:25:28.863641,0.0000,NaN,16385,Texto,telegram,NaN,NaN
1,2022-10-05 06:25:08,NaN,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,"Saiu no YouTube do presidente a 8 horas atrás,...",5,2022-10-05 06:25:28.926311,0.0644,NaN,16386,Texto,telegram,NaN,NaN
2,2022-10-05 06:26:28,92a2d8fd7144074f659d1d29dc3751da,9f2d7394334eb224c061c9740b5748fc,NaN,NaN,NaN,False,False,False,"É isso, nossa parte já foi quase toda feita. N...",5,2022-10-05 06:26:29.361949,-0.3551,0.157242,16366,Texto,telegram,NaN,NaN
3,2022-10-05 06:27:28,d60aa38f62b4977426b70944af4aff72,c8f2de56550ed0bf85249608b7ead93d,94dca4cda503100ebfda7ce2bcc060eb.jpg,image/jpg,NaN,True,False,False,GENTE ACHEI ELES EM UMA SEITA MAÇONÁRICA,5,2022-10-05 06:27:29.935624,0.0000,NaN,19281,Imagem,telegram,NaN,94dca4cda503100ebfda7ce2bcc060eb
4,2022-10-05 06:27:44,cd6979b0b5265f08468fa1689b6300ce,e56ec342fc599ebb4ed89655eb6f03aa,5ad5c8bbe9da93a37fecf3e5aa5b0637.jpg,image/jpg,NaN,True,False,False,NaN,5,2022-10-05 06:28:29.316325,NaN,NaN,507185,Imagem,telegram,NaN,5ad5c8bbe9da93a37fecf3e5aa5b0637
5,2022-10-05 06:28:30,NaN,b52442a5fbc459ae590dca0d215e32f9,NaN,NaN,NaN,False,False,False,Kķkkkkk to rindo até agora....Quem disse q ia ...,5,2022-10-05 06:29:29.046694,0.7003,0.197813,2735,Texto,telegram,NaN,NaN
6,2022-10-05 06:29:09,3b685d44ff197b98d7c9e99b8f6b5281,b52442a5fbc459ae590dca0d215e32f9,NaN,NaN,NaN,False,False,False,*SE ALGUÉM TE PERGUNTAR O QUE FOI QUE BOLSONAR...,5,2022-10-05 06:29:29.33448,0.9716,0.974258,2736,Texto,telegram,NaN,NaN
7,2022-10-05 06:43:51,a7db4ff6a6d35e57be5bcf02f400cec6,857cd5311da1bdc15eb9e6918a47c6c6,4fe93a3772445f64173ef03db1fed83c.jpg,image/jpg,NaN,True,False,False,NaN,5,2022-10-05 06:43:54.51408,NaN,NaN,891535,Imagem,telegram,NaN,4fe93a3772445f64173ef03db1fed83c
8,2022-10-05 07:09:39,d2c33afd13a3165be031b6c244f7140d,d9c080b9db8cd9d0e88e870ce782c01a,30f29cca618753961cb97be95e87e3b4.jpg,image/jpg,NaN,True,False,False,NaN,5,2022-10-05 07:10:16.569761,NaN,NaN,314861,Imagem,telegram,NaN,30f29cca618753961cb97be95e87e3b4
9,2022-10-05 06:29:48,a7e85072244cae15446c9d517dc01a1a,b8a8737812c7fd7d3e0bdbb65ef6306f,NaN,NaN,www.marketingdigitalparavencer.com.br,False,True,False,O Deputado Federal pelo NOVO e que foi candida...,5,2022-10-05 06:29:49.901419,-0.8779,0.035876,7248,Texto,telegram,NaN,NaN

In [4]:
df.describe()

       dataset_info_id  score_sentiment  score_misinformation    id_message
count         557586.0    444157.000000         167238.000000  5.575860e+05
mean               5.0         0.017330              0.312245  4.450617e+05
std                0.0         0.464165              0.293699  4.860211e+05
min                5.0        -1.000000              0.000003  2.000000e+00
25%                5.0        -0.177900              0.078454  2.127500e+04
50%                5.0         0.000000              0.197577  1.210935e+05
75%                5.0         0.318200              0.490351  9.726045e+05
max                5.0         0.999200              1.000000  1.516436e+06

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 557586 entries, 0 to 557585
Data columns (total 19 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   date_message            557586 non-null  object
 1   id_member_anonymous     234245 non-null  object
 2   id_group_anonymous      557586 non-null  object
 3   media                   332605 non-null  object
 4   media_type              332605 non-null  object
 5   media_url               157445 non-null  object
 6   has_media               557586 non-null  bool
 7   has_media_url           557586 non-null  bool
 8   trava_zap               557586 non-null  bool
 9   text_content_anonymous  444201 non-null  object
 10  dataset_info_id         557586 non-null  int64
 11  date_system             557586 non-null  object
 12  score_sentiment         444157 non-null  float64
 13  score_misinformation    167238 non-null  float64
 14  id_message              557586 non-null  int64
 15  message_type            557586 non-null  object
 16  messenger               557586 non-null  object
 17  media_name              28987 non-null   object
 18  media_md5               332605 non-null  object
dtypes: bool(3), float64(2), int64(2), object(12)
memory usage: 69.7+ MB

## b) Identificar e listar as posições (células) contendo valores faltantes

É utilizado a função `isnull` do Pandas, que retorna um dataframe do mesmo tamanho do original, mas com as celúlas preenchindas com False ou True, facilitando a listagem das posiçõoes contendo valores nulos.

In [6]:
null_cells = df.isnull()
null_positions = [(row, col) for row, cols in null_cells.iterrows() for col, is_null in cols.items() if is_null]

In [7]:
null_cells

,date_message,id_member_anonymous,id_group_anonymous,media,media_type,media_url,has_media,has_media_url,trava_zap,text_content_anonymous,dataset_info_id,date_system,score_sentiment,score_misinformation,id_message,message_type,messenger,media_name,media_md5
0,False,False,False,True,True,True,False,False,False,False,False,False,False,True,False,False,False,True,True
1,False,True,False,True,True,True,False,False,False,False,False,False,False,True,False,False,False,True,True
2,False,False,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,True,True
3,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True,False
4,False,False,False,False,False,True,False,False,False,True,False,False,True,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557581,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False
557582,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False
557583,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False
557584,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False
557585,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False

In [8]:
print("Cells with missing values:")
null_positions[:50]

Cells with missing values:

[(0, 'media'),
 (0, 'media_type'),
 (0, 'media_url'),
 (0, 'score_misinformation'),
 (0, 'media_name'),
 (0, 'media_md5'),
 (1, 'id_member_anonymous'),
 (1, 'media'),
 (1, 'media_type'),
 (1, 'media_url'),
 (1, 'score_misinformation'),
 (1, 'media_name'),
 (1, 'media_md5'),
 (2, 'media'),
 (2, 'media_type'),
 (2, 'media_url'),
 (2, 'media_name'),
 (2, 'media_md5'),
 (3, 'media_url'),
 (3, 'score_misinformation'),
 (3, 'media_name'),
 (4, 'media_url'),
 (4, 'text_content_anonymous'),
 (4, 'score_sentiment'),
 (4, 'score_misinformation'),
 (4, 'media_name'),
 (5, 'id_member_anonymous'),
 (5, 'media'),
 (5, 'media_type'),
 (5, 'media_url'),
 (5, 'media_name'),
 (5, 'media_md5'),
 (6, 'media'),
 (6, 'media_type'),
 (6, 'media_url'),
 (6, 'media_name'),
 (6, 'media_md5'),
 (7, 'media_url'),
 (7, 'text_content_anonymous'),
 (7, 'score_sentiment'),
 (7, 'score_misinformation'),
 (7, 'media_name'),
 (8, 'media_url'),
 (8, 'text_content_anonymous'),
 (8, 'score_sentiment'),
 (8, 'score_misinformation'),
 (8, 'media_name'),
 (9, 'media'),
 (9, 'media_type'),
 (9, 'media_name')]

In [9]:
print("Amount of cells with missing values:")
len(null_positions)

Amount of cells with missing values:

2544186

## c) Contar quantas linhas possuem valores faltantes

É utilizada a mesma função do item anterior. Porém com a função `any`, que retorna True se qualquer valor em uma linha também é True, ou seja, se pelo menos um valor na linha for nulo.

In [10]:
count_null_rows = df.isnull().any(axis=1).sum()

In [11]:
print("Amount of rows with missing values")
count_null_rows

Amount of rows with missing values

np.int64(557561)

In [12]:
print("Amount of rows with no missing values")
len(df) - count_null_rows

Amount of rows with no missing values

np.int64(25)

## d) Para cada coluna (feature), contar quantas linhas possuem valores faltantes

Seguimos utilizando a função `isnull` porém agora somando os valores. Resultando assim na quantidade de valores faltantes por coluna, já que True == 1.

In [13]:
missing_per_column = df.isnull().sum()

In [14]:
print("Amount of missing values per column")
missing_per_column

Amount of missing values per column

date_message                   0
id_member_anonymous       323341
id_group_anonymous             0
media                     224981
media_type                224981
media_url                 400141
has_media                      0
has_media_url                  0
trava_zap                      0
text_content_anonymous    113385
dataset_info_id                0
date_system                    0
score_sentiment           113429
score_misinformation      390348
id_message                     0
message_type                   0
messenger                      0
media_name                528599
media_md5                 224981
dtype: int64

## e) Identificar e listar as linhas repetidas (duplicadas)

Utilizamos a função `duplicated` do Pandas e criamos um dataset novo apenas com as linhas duplicadas.

In [15]:
duplicated_rows = df[df.duplicated()]

In [16]:
print("Duplicated rows:")
duplicated_rows

Duplicated rows:

Empty DataFrame
Columns: [date_message, id_member_anonymous, id_group_anonymous, media, media_type, media_url, has_media, has_media_url, trava_zap, text_content_anonymous, dataset_info_id, date_system, score_sentiment, score_misinformation, id_message, message_type, messenger, media_name, media_md5]
Index: []

## f) Identificar e listar as posições (células) contendo valores que não pertencem ao domínio (tipo de dados) esperado

Para verificar se há valores que não pertencem ao tipo de dado esperado por coluna, primeiro são removidos os valores nulos com `dropna()`, pois eles podem interferir na verificação dos tipos.

Em seguida, é feita uma varredura em cada coluna do dataframe limpo, coletando os tipos de dados presentes em cada uma.

In [17]:
df_clean = df.dropna()
column_types = []
for column in df_clean.columns:
    existing_types = {type(value) for value in df_clean[column]}
    column_types.append((column, existing_types))

In [18]:
print("Column types:")
column_types

Column types:

[('date_message', {str}),
 ('id_member_anonymous', {str}),
 ('id_group_anonymous', {str}),
 ('media', {str}),
 ('media_type', {str}),
 ('media_url', {str}),
 ('has_media', {bool}),
 ('has_media_url', {bool}),
 ('trava_zap', {bool}),
 ('text_content_anonymous', {str}),
 ('dataset_info_id', {int}),
 ('date_system', {str}),
 ('score_sentiment', {float}),
 ('score_misinformation', {float}),
 ('id_message', {int}),
 ('message_type', {str}),
 ('messenger', {str}),
 ('media_name', {str}),
 ('media_md5', {str})]

## g) Crie uma coluna chamada “caracteres” contendo a quantidade de caracteres da coluna “text”

É utilizada a função apply do Pandas em conjunto com uma função lambda, que aplica `len(x)` para medir o comprimento de cada string. Caso o valor da célula seja nulo, a função retorna `0`.

In [19]:
df['caracteres'] = df['text_content_anonymous'].apply(lambda x: len(x) if pd.notnull(x) else 0)
df['caracteres']

0         110
1         141
2         350
3          40
4           0
         ...
557581    152
557582     28
557583     68
557584     68
557585     68
Name: caracteres, Length: 557586, dtype: int64

In [20]:
df['caracteres'].describe()

count    557586.000000
mean        172.457422
std         373.584693
min           0.000000
25%          22.000000
50%          83.000000
75%         167.000000
max        4096.000000
Name: caracteres, dtype: float64

## h) Crie uma coluna chamada “words” contendo a quantidade de palavras da coluna “text”

Utilizamos a mesma lógica do item anterior, porém, ao invés de calcular o número de caracteres, calculamos o número de palavras. Para isso, a função `split()` é usada para separar o texto em palavras, e o método `len()` conta quantas palavras foram extraídas.

In [21]:
df['words'] = df['text_content_anonymous'].apply(lambda x: len(x.split()) if pd.notnull(x) else 0)
df['words']

0         20
1         23
2         59
3          7
4          0
          ..
557581    12
557582     1
557583     6
557584     6
557585     6
Name: words, Length: 557586, dtype: int64

In [22]:
df['words'].describe()

count    557586.000000
mean         25.870721
std          61.178617
min           0.000000
25%           1.000000
50%          12.000000
75%          24.000000
max        1261.000000
Name: words, dtype: float64

## i) Crie uma coluna chamada “viral” contendo o valor 0 se o texto da mensagem (valor do campo “text”) não for encontrado em outras linhas e 1, caso contrário

Para identificar se um texto é "viral", usamos a função `value_counts()` do Pandas para contar a ocorrência de cada valor na coluna `text_content_anonymous`.

Se o texto aparecer mais de uma vez no dataframe, o texto é considerado "viral" e recebe o valor `1`. Caso contrário, recebe o valor `0`.

In [23]:
text_counts = df['text_content_anonymous'].value_counts()
df['viral'] = df['text_content_anonymous'].apply(lambda x: 1 if pd.notnull(x) and text_counts[x] > 1 else 0)
df['viral']

0         0
1         0
2         0
3         0
4         0
         ..
557581    1
557582    1
557583    1
557584    1
557585    1
Name: viral, Length: 557586, dtype: int64

In [24]:
print('Amount of viral texts:')
len(df[df['viral'] == 1])

Amount of viral texts:

226537

## j) Crie uma coluna chamada “sharings” contendo a quantidade de vezes que o texto armazenado no atributo “text” aparece no dataset

Para contar o número de vezes que cada texto aparece no dataset, reutilizamos a variável `text_counts` do item anterior, que contém a contagem de ocorrências de cada valor na coluna `text_content_anonymous`

In [25]:
df['sharings'] = df['text_content_anonymous'].apply(lambda x: text_counts[x] if pd.notnull(x) else 0) # utilizando a mesma variável do item anterior
df['sharings']

0         1
1         1
2         1
3         1
4         0
         ..
557581    2
557582    2
557583    4
557584    4
557585    4
Name: sharings, Length: 557586, dtype: int64

In [26]:
print('Top 10 viral texts:')
text_counts.head(10)

Top 10 viral texts:

text_content_anonymous
This community was blocked in Brazil following a decision of the Superior Electoral Court (TSE).                                                                                                                                                                                                                                                                                                                                                                                        17422
Rough_sex🙈                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1134
Anal sex🙈                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1118
سکس مردان ازبک با زن انگلیسی با این vpn از سایتهای ممنوعه ببینید🙈\n\nشاهد الرجال الأوزبكيين يمارسون الجنس مع النساء الإنجليزيات باستخدام VPN هذا من المواقع المحظورة🚫\n\nTaqiqlangan saytlardan bu vpn orqali o'zbek erkaklari ingliz ayollari bilan jinsiy aloqa qilishlarini ko'ring\n\nSee Uzbek men having sex with English women with this vpn from banned sites                                                                                                                    1019
https://youtu.be/qbTzhB0akt8                                                                                                                                                                                                                                                                                                                                                                                                                                                              758
https://youtu.be/zDuOoyhyN-4                                                                                                                                                                                                                                                                                                                                                                                                                                                              712
فیلم سوپر با زیرنویس فارسی ببین😍😍\nبا این فیلترشکن میتونی هروقت دلت خواست فیلم سوپر ببینی😍\n\nAmerikalik ayolni arab erkaklari tomonidan zo'rlanganini ushbu vpn bilan tomosha qiling\nFaqat 18 yoshdan oshganlar\n\nWatch the rape of an American woman by Arab men with this vpn\nOnly people over 18 years old                                                                                                                                                                         632
Rough😱                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    570
Foto de Nélia Barros                                                                                                                                                                                                                                                                                                                                                                                                                                                                      548
We had no choice but to remain in the shadows.  \nThey intended to eliminate [us].  \nThey wish to destroy what they are unable to control. \nWe are ready to emerge from the shadows. THE TIME HAS COME! \n \nYou only have a few hours to join this channel before it goes private! After that, only those who are invited will be able to see what I have to [REVEAL] – tonight - midnight. \n \nYou have a choice. Take a look around! \n \n❗️ТYРЕ lN ЅЕАRСН ВАR: theQwakening17      480
Name: count, dtype: int64

## k) Crie uma coluna chamada “sentiment” contendo os valores: -1 para textos negativos, 0 para textos neutros e 1 para textos positivos

A coluna sentiment é criada com base nos valores da coluna `score_sentiment`, que contém os resultados de uma análise de sentimento.

O valor de sentiment é atribuído de acordo com o seguinte critério:

* 1 para textos com sentimento positivo (quando o valor de score_sentiment for maior ou igual que 0.05)

* 0 para textos com sentimento neutro (quando o valor de score_sentiment for entre -0.05 e 0.05)

* -1 para textos com sentimento negativo (quando o valor de score_sentiment for menor ou igual que -0.05)

In [27]:
df['sentiment'] = df['score_sentiment'].apply(lambda x: 1 if x >= 0.05 else (-1 if x <= -0.05 else 0))
df['sentiment']

0         0
1         1
2        -1
3         0
4         0
         ..
557581    1
557582    0
557583    0
557584    0
557585    0
Name: sentiment, Length: 557586, dtype: int64

In [28]:
df['score_sentiment'].describe()

count    444157.000000
mean          0.017330
std           0.464165
min          -1.000000
25%          -0.177900
50%           0.000000
75%           0.318200
max           0.999200
Name: score_sentiment, dtype: float64

## l) Eliminar as linhas cujo valor da coluna “text” contenham “trava-zaps”

Consideramos que a coluna `trava_zap` já possui valores corretos que indicam se o texto contém ou não o termo "trava-zaps".

Portanto, para eliminar as linhas em que a coluna `trava_zap` é igual a True (indicando que o texto contém "trava-zaps"), podemos simplesmente filtrar o dataframe e manter as linhas onde trava_zap seja diferente de True.

In [29]:
df_without_travazap = df[df['trava_zap'] != True]

In [30]:
df_without_travazap.head(10)

,date_message,id_member_anonymous,id_group_anonymous,media,media_type,media_url,has_media,has_media_url,trava_zap,text_content_anonymous,...,id_message,message_type,messenger,media_name,media_md5,caracteres,words,viral,sharings,sentiment
0,2022-10-05 06:25:04,1078cc958f0febe28f4d03207660715f,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,Então é Fato Renato o áudio que eu ouvi no wha...,...,16385,Texto,telegram,NaN,NaN,110,20,0,1,0
1,2022-10-05 06:25:08,NaN,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,"Saiu no YouTube do presidente a 8 horas atrás,...",...,16386,Texto,telegram,NaN,NaN,141,23,0,1,1
2,2022-10-05 06:26:28,92a2d8fd7144074f659d1d29dc3751da,9f2d7394334eb224c061c9740b5748fc,NaN,NaN,NaN,False,False,False,"É isso, nossa parte já foi quase toda feita. N...",...,16366,Texto,telegram,NaN,NaN,350,59,0,1,-1
3,2022-10-05 06:27:28,d60aa38f62b4977426b70944af4aff72,c8f2de56550ed0bf85249608b7ead93d,94dca4cda503100ebfda7ce2bcc060eb.jpg,image/jpg,NaN,True,False,False,GENTE ACHEI ELES EM UMA SEITA MAÇONÁRICA,...,19281,Imagem,telegram,NaN,94dca4cda503100ebfda7ce2bcc060eb,40,7,0,1,0
4,2022-10-05 06:27:44,cd6979b0b5265f08468fa1689b6300ce,e56ec342fc599ebb4ed89655eb6f03aa,5ad5c8bbe9da93a37fecf3e5aa5b0637.jpg,image/jpg,NaN,True,False,False,NaN,...,507185,Imagem,telegram,NaN,5ad5c8bbe9da93a37fecf3e5aa5b0637,0,0,0,0,0
5,2022-10-05 06:28:30,NaN,b52442a5fbc459ae590dca0d215e32f9,NaN,NaN,NaN,False,False,False,Kķkkkkk to rindo até agora....Quem disse q ia ...,...,2735,Texto,telegram,NaN,NaN,133,25,0,1,1
6,2022-10-05 06:29:09,3b685d44ff197b98d7c9e99b8f6b5281,b52442a5fbc459ae590dca0d215e32f9,NaN,NaN,NaN,False,False,False,*SE ALGUÉM TE PERGUNTAR O QUE FOI QUE BOLSONAR...,...,2736,Texto,telegram,NaN,NaN,3669,618,0,1,1
7,2022-10-05 06:43:51,a7db4ff6a6d35e57be5bcf02f400cec6,857cd5311da1bdc15eb9e6918a47c6c6,4fe93a3772445f64173ef03db1fed83c.jpg,image/jpg,NaN,True,False,False,NaN,...,891535,Imagem,telegram,NaN,4fe93a3772445f64173ef03db1fed83c,0,0,0,0,0
8,2022-10-05 07:09:39,d2c33afd13a3165be031b6c244f7140d,d9c080b9db8cd9d0e88e870ce782c01a,30f29cca618753961cb97be95e87e3b4.jpg,image/jpg,NaN,True,False,False,NaN,...,314861,Imagem,telegram,NaN,30f29cca618753961cb97be95e87e3b4,0,0,0,0,0
9,2022-10-05 06:29:48,a7e85072244cae15446c9d517dc01a1a,b8a8737812c7fd7d3e0bdbb65ef6306f,NaN,NaN,www.marketingdigitalparavencer.com.br,False,True,False,O Deputado Federal pelo NOVO e que foi candida...,...,7248,Texto,telegram,NaN,NaN,1242,153,0,1,-1

In [31]:
df_without_travazap.describe()

,dataset_info_id,score_sentiment,score_misinformation,id_message,caracteres,words,viral,sharings,sentiment
count,557570.0,444141.000000,167224.000000,5.575700e+05,557570.000000,557570.000000,557570.000000,557570.000000,557570.000000
mean,5.0,0.017326,0.312263,4.450694e+05,172.462371,25.871464,0.406293,564.713803,0.011731
std,0.0,0.464169,0.293703,4.860235e+05,373.588911,61.179338,0.491141,3029.336944,0.683324
min,5.0,-1.000000,0.000003,2.000000e+00,0.000000,0.000000,0.000000,0.000000,-1.000000
25%,5.0,-0.177900,0.078466,2.127425e+04,22.000000,1.000000,0.000000,1.000000,0.000000
50%,5.0,0.000000,0.197592,1.211015e+05,83.000000,12.000000,0.000000,1.000000,0.000000
75%,5.0,0.318200,0.490396,9.726088e+05,167.000000,24.000000,1.000000,4.000000,0.000000
max,5.0,0.999200,1.000000,1.516436e+06,4096.000000,1261.000000,1.000000,17422.000000,1.000000

In [32]:
print('Amount of rows without "trava-zaps":')
len(df[df['trava_zap'] == True])

Amount of rows without "trava-zaps":

16

## m) Identificar inconsistências entre os atributos (features)

Neste item, vamos verificar se existem inconsistências nas colunas do dataframe original. Será verificado as possíveis inconsistências seguintes:

* **Verificação da coluna `trava_zap`**: Verificar se os valores desta coluna estão corretos, garantindo que o valor True corresponde a textos que realmente contêm "trava-zaps" e o valor False para os demais.
* **Verificação de IDs duplicados**: Verificar se a coluna que armazena os IDs possui valores duplicados.
* **Verificação da coluna `has_media`**: Verificar se a coluna `has_media` está correta, ou seja, se um valor True indica a presença de mídia e False indica a ausência.
* **Verificação da coluna `has_media_url`**: Verificar se a coluna `has_media_url` está correta, ou seja, se True indica que uma URL de mídia está presente na coluna `media_url` e False indica sua ausência.

### Inconsistências na coluna `trava_zap`

In [33]:
def has_trava_zap(message):
  if not isinstance(message, str):
    return False  # Garante que só analisa strings

  # Regra 1: muito longo
  if len(message) > 10000:
    return True

  # Regra 2: caracteres invisíveis
  invisible = ''.join(chr(c) for c in range(0x200B, 0x200F + 1)) + '\uFEFF'
  if sum(message.count(c) for c in invisible) > 100:
    return True

  # Regra 3: emojis repetidos
  emoji_pattern = re.compile("[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF"
                              "\U0001F680-\U0001F6FF\U0001F1E0-\U0001F1FF]+", flags=re.UNICODE)
  emojis = emoji_pattern.findall(message)
  if any(len(e) > 20 for e in emojis):
    return True

  # Regra 4: baixa diversidade
  unique = set(message)
  if len(unique) < 10 and len(message) > 500:
    return True

  return False

In [34]:
df['has_travazap2'] = df['text_content_anonymous'].apply(has_trava_zap)

In [35]:
tp = ((df['has_travazap2'] == True) & (df['trava_zap'] == True)).sum()
tn = ((df['has_travazap2'] == False) & (df['trava_zap'] == False)).sum()
fp = ((df['has_travazap2'] == True) & (df['trava_zap'] == False)).sum()
fn = ((df['has_travazap2'] == False) & (df['trava_zap'] == True)).sum()

print(f"False Positives (FP): {fp}")
print(f"False Negatives (FN): {fn}")

accuracy = (tp + tn) / (tp + tn + fp + fn)
print(f"Accuracy: {accuracy:.2%}")

False Positives (FP): 1281
False Negatives (FN): 16
Accuracy: 99.77%

In [36]:
mismatches = df[df['has_travazap2'] != df['trava_zap']]
print(f"Number of mismatches: {len(mismatches)}")
mismatches.head()

Number of mismatches: 1297

,date_message,id_member_anonymous,id_group_anonymous,media,media_type,media_url,has_media,has_media_url,trava_zap,text_content_anonymous,...,message_type,messenger,media_name,media_md5,caracteres,words,viral,sharings,sentiment,has_travazap2
46,2022-10-05 07:01:49,f482bce90a9407e20634bf3d3660558e,c8f2de56550ed0bf85249608b7ead93d,NaN,NaN,NaN,False,False,False,CCCCCCCCCCCCCCCCCCCCCCCHHHHHHHHHHHHHHHHHHHHHOO...,...,Texto,telegram,NaN,NaN,364,28,0,1,0,True
75,2022-10-05 07:41:10,NaN,b52442a5fbc459ae590dca0d215e32f9,NaN,NaN,https://www.jornaldacidadeonline.com.br/notici...,False,True,False,A juíza substituta da 6ª Vara Criminal de Lond...,...,Texto,telegram,NaN,NaN,2557,431,1,2,-1,True
117,2022-10-05 08:02:17,f482bce90a9407e20634bf3d3660558e,c8f2de56550ed0bf85249608b7ead93d,NaN,NaN,NaN,False,False,False,CCCCCCCCCCCCCCCCCCCCCCCHHHHHHHHHHHHHHHHHHHHHOO...,...,Texto,telegram,NaN,NaN,4096,1261,1,3,0,True
1045,2022-10-05 11:20:48,NaN,0e899038fbe9196d404c90cf7ad282e0,NaN,NaN,NaN,False,False,False,No dia 30/10 vamos todos de verde e amarelo vo...,...,Texto,telegram,NaN,NaN,75,11,1,2,0,True
1103,2022-10-05 11:31:07,NaN,b11f2df64ac19aad47a50accf32052d6,NaN,NaN,NaN,False,False,False,POVOOOOOOO ACORDA !!!!!!HOJE A LIVE DO NOSSO ...,...,Texto,telegram,NaN,NaN,316,28,0,1,-1,True

In [37]:
df.drop(columns=['has_travazap2'], inplace=True)

### Inconsistências nos IDs

Há IDs (`id_message`) duplicados?

In [38]:
duplicated_ids = df[df.duplicated('id_message', keep=False)]

In [39]:
print(f"Amount of rows with duplicated ids: {len(duplicated_ids)}")
duplicated_ids.sort_values(by='id_message').head(10)

Amount of rows with duplicated ids: 251533

,date_message,id_member_anonymous,id_group_anonymous,media,media_type,media_url,has_media,has_media_url,trava_zap,text_content_anonymous,...,id_message,message_type,messenger,media_name,media_md5,caracteres,words,viral,sharings,sentiment
239076,2022-09-30 10:39:16,NaN,1a6d329637e0407152d98b93ef75506a,cfa2c6e29fabc9f87c4b5e57e2f8a422.jpg,image/jpg,NaN,True,False,False,"Confie em mim com esta plataforma, não acho qu...",...,103,Imagem,telegram,NaN,cfa2c6e29fabc9f87c4b5e57e2f8a422,306,51,1,86,1
174184,2022-10-08 22:59:35,17b0ce09f9960e4e6b27278a8368cb3b,eff93933ee611fcb65b70c399f771a5b,b5ab97b82ce9a3957022b7388d8fb910.apk,application/vnd.android.package-archive,NaN,True,False,False,Lesbian👩‍❤‍👩,...,103,Application,telegram,لزبین.apk,b5ab97b82ce9a3957022b7388d8fb910,12,1,1,359,0
174153,2022-10-08 22:59:35,7427a46c87258eef4ea3a6745356f2af,eff93933ee611fcb65b70c399f771a5b,b5ab97b82ce9a3957022b7388d8fb910.apk,application/vnd.android.package-archive,NaN,True,False,False,Lesbian👩‍❤‍👩,...,104,Application,telegram,لزبین.apk,b5ab97b82ce9a3957022b7388d8fb910,12,1,1,359,0
239914,2022-09-30 10:39:17,NaN,1a6d329637e0407152d98b93ef75506a,5743873090f919134ed597ee371857b5.jpg,image/jpg,NaN,True,False,False,[USER] VOCÊ É O MELHOR GERENTE OBRIGADO PELA A...,...,104,Imagem,telegram,NaN,5743873090f919134ed597ee371857b5,69,11,1,23,1
174176,2022-10-08 22:59:35,7427a46c87258eef4ea3a6745356f2af,eff93933ee611fcb65b70c399f771a5b,b5ab97b82ce9a3957022b7388d8fb910.apk,application/vnd.android.package-archive,NaN,True,False,False,Lesbian👩‍❤‍👩,...,106,Application,telegram,لزبین.apk,b5ab97b82ce9a3957022b7388d8fb910,12,1,1,359,0
239913,2022-09-30 10:39:17,NaN,1a6d329637e0407152d98b93ef75506a,bfc11043f3a0a8bf7c1bfe14b7ba096f.jpg,image/jpg,NaN,True,False,False,"Feedback de Anderson Martinho 29 anos. Brasil,...",...,106,Imagem,telegram,NaN,bfc11043f3a0a8bf7c1bfe14b7ba096f,138,22,1,49,1
240174,2022-09-30 13:33:51,NaN,1a6d329637e0407152d98b93ef75506a,b941001b26cbeb5fdf36db8b0fe35435.jpg,image/jpg,NaN,True,False,False,"Feedback de Paulo Casado 24 anos. Brazil, Vitó...",...,108,Imagem,telegram,NaN,b941001b26cbeb5fdf36db8b0fe35435,146,24,1,11,1
174204,2022-10-08 22:59:35,7427a46c87258eef4ea3a6745356f2af,eff93933ee611fcb65b70c399f771a5b,b5ab97b82ce9a3957022b7388d8fb910.apk,application/vnd.android.package-archive,NaN,True,False,False,Lesbian👩‍❤‍👩,...,108,Application,telegram,لزبین.apk,b5ab97b82ce9a3957022b7388d8fb910,12,1,1,359,0
240175,2022-09-30 13:33:51,NaN,1a6d329637e0407152d98b93ef75506a,e985dd0e458bcac9e1c4fc0a8275ae34.jpg,image/jpg,NaN,True,False,False,"Feedback de Nelson Aranha 23 anos. Brazil, Oli...",...,109,Imagem,telegram,NaN,e985dd0e458bcac9e1c4fc0a8275ae34,133,22,1,28,1
173852,2022-10-08 22:59:35,7427a46c87258eef4ea3a6745356f2af,eff93933ee611fcb65b70c399f771a5b,b5ab97b82ce9a3957022b7388d8fb910.apk,application/vnd.android.package-archive,NaN,True,False,False,Lesbian👩‍❤‍👩,...,109,Application,telegram,لزبین.apk,b5ab97b82ce9a3957022b7388d8fb910,12,1,1,359,0

### Inconsistência na mídias

1. Inconsistências na coluna `has_media`

In [40]:
incorrect_has_media = df[((df['has_media'] == True) & df['media'].isnull()) | ((df['has_media'] == False) & df['media'].notnull())]

In [41]:
incorrect_has_media

Empty DataFrame
Columns: [date_message, id_member_anonymous, id_group_anonymous, media, media_type, media_url, has_media, has_media_url, trava_zap, text_content_anonymous, dataset_info_id, date_system, score_sentiment, score_misinformation, id_message, message_type, messenger, media_name, media_md5, caracteres, words, viral, sharings, sentiment]
Index: []

[0 rows x 24 columns]

2. Inconsistências na coluna `has_media_url`

In [42]:
incorrect_has_media_url = df[(df['has_media_url'] == True) & df['media_url'].isnull()]
incorrect_has_media_url

Empty DataFrame
Columns: [date_message, id_member_anonymous, id_group_anonymous, media, media_type, media_url, has_media, has_media_url, trava_zap, text_content_anonymous, dataset_info_id, date_system, score_sentiment, score_misinformation, id_message, message_type, messenger, media_name, media_md5, caracteres, words, viral, sharings, sentiment]
Index: []

[0 rows x 24 columns]

---

![MDCC](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpPMiWU_DtYHDxAG5A3icfDwguLHmjzSqK7w&s)